---------- CATEGORIAS DE CADA ANIME ---------- 
CREATE SEQUENCE IF NOT EXISTS SQ_ANIME_CATEGORIA START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_ANIME_CATEGORIA(
    ID BIGINT NOT NULL DEFAULT NEXTVAL('SQ_ANIME_CATEGORIA'),
    ID_CATEGORIA BIGINT NOT NULL,
    ID_ANIME BIGINT NOT NULL,
    CONSTRAINT PK_ANIME_CATEGORIA PRIMARY  KEY (ID),
    CONSTRAINT FK_ANIME_CATEGORIA_ANIME FOREIGN KEY (ID_ANIME) REFERENCES PUBLIC.TB_ANIME (ID),    
    CONSTRAINT FK_ANIME_CATEGORIA_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES PUBLIC.TB_CATEGORIA (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_ANIME_CATEGORIA ON PUBLIC.TB_ANIME_CATEGORIA (ID_CATEGORIA,ID_ANIME);
