services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    networks:
      - rede_interna
    depends_on: 
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    
    networks:
      - rede_interna


networks:
  rede_interna:
    driver: bridge
