CREATE SEQUENCE IF NOT EXISTS SQ_USUARIO START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS TB_USUARIO(
   	ID BIGINT NOT NULL DEFAULT NEXTVAL('SQ_USUARIO'),
    NOME VARCHAR(100) NOT null,
   	PASSWORD TEXT NOT null,
    CRIADO TIMESTAMP default NOW(),
    CONSTRAINT PK_USUARIO PRIMARY KEY(ID),
    IND_ADMIN BOOL
    );

CREATE UNIQUE INDEX IF NOT EXISTS UNQ_USUARIO_NOME ON TB_USUARIO(NOME);
