---------- EPISODIOS ---------- 
CREATE SEQUENCE IF NOT EXISTS SQ_EPISODIO START WITH 1 INCREMENT BY 1;


CREATE TABLE TB_EPISODIO(
    ID BIGINT NOT NULL DEFAULT NEXTVAL('SQ_EPISODIO'),
    SEGUNDOS BIGINT NOT NULL,
    MINUTOS_CALCULADO BIGINT,
    SEGUNDOS_CALCULADO BIGINT,
    DATA_UPLOAD DATE,
    TEMPORADA BIGINT,
    ID_ANIME BIGINT NOT NULL,
    CONSTRAINT PK_EPISODIO PRIMARY  KEY (ID),
    CONSTRAINT FK_EPISODIO_ANIME FOREIGN KEY (ID_ANIME) REFERENCES PUBLIC.TB_ANIME (ID)    
);

COMMIT;
 

-- !!!!!Criar gatilho que calcula os minutos e segundos a cada alteracao em SEGUNDOS!!!!!


